### ISSUE TITLE
Penamaan Variabel

### ISSUE THREAD

**Issue by fhyfr** [suryabk/beclass-final#1]
- Untuk penamaan variabel lebih baik pakai camelCase ya daripada snake_case
- Kalau nama kolom baru bagusnya pakai snake_case
- nama folder `pict` mending diubah jadi `picture` atau `images` sekalian aja biar tahu kalau isinya itu gambar dan ngga rancu
- Di dalam folder `asset` juga bisa dikelompokan lagi lebih spesifik, misalkan folder khusus `css`, `templates`, etc

**Comment by fhyfr** [comment]
Lebih bagus lagi kalau di readme dijelaskan lagi cara instalasi project nya

**Comment by suryabk** [comment]
makasih masukannya bang. Sudah saya perbaiki. Tapi, readme nya belom saya ganti

**Comment by suryabk** [comment]
readme sudah saya ganti bang

**Comment by fhyfr** [comment]
Mantapp, jempull
